name: Check the metadata is up-to-date
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/check.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-24.04

    outputs:
      matrix: ${{ steps.resolve.outputs.matrix }}

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: resolve
        name: Get every branches
        run: |
          REMOTE=($(git branch -r | grep -v 'main' | sed -e 's/origin\///'))
          MATRIX=$(jq -cn '{branch: $ARGS.positional}' --args "${REMOTE[@]}")
          echo "${REMOTE[@]} -> ${MATRIX}"
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  check:
    name: Check the metadata is up-to-date
    needs: setup
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false

    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - id: check
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork --commit-only manifest.yaml

      - id: push
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ matrix.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
